using Teyemer.Core;
using Teyemer.Infrastructure;
var tests=new(string,Func<Task>)[]{("일반 활성",()=>Sync(()=>A.True(ScheduleEvaluator.Evaluate(At(17,10),D()).IsActive))),("경계",()=>Sync(Boundaries)),("비활성 요일",()=>Sync(()=>A.False(ScheduleEvaluator.Evaluate(At(16,10),D()).IsActive))),("자정 통과",()=>Sync(Overnight)),("일-월 경계",()=>Sync(SundayMonday)),("주기 변경",()=>Sync(IntervalChange)),("다시 알림",()=>Sync(Snooze)),("일시정지",()=>Sync(Pause)),("미누적",()=>Sync(NoBacklog)),("세션 복귀",()=>Sync(SessionResume)),("손상 설정",CorruptSettings),("경로 인용",()=>Sync(StartupQuote)),("자동 닫힘 범위",()=>Sync(PopupRange))};
var failed=0;foreach(var t in tests){try{await t.Item2();Console.WriteLine($"PASS {t.Item1}");}catch(Exception e){failed++;Console.Error.WriteLine($"FAIL {t.Item1}: {e.Message}");}}Console.WriteLine($"{tests.Length-failed}/{tests.Length} tests passed");return failed==0?0:1;
static Task Sync(Action a){a();return Task.CompletedTask;}static AppSettings D()=>AppSettings.CreateDefault();static DateTimeOffset At(int day,int hour,int min=0)=>new(2026,8,day,hour,min,0,TimeSpan.FromHours(9));
static ReminderEngine E(DateTimeOffset n,int m=20){var s=D();s.ActiveScheduleEnabled=false;s.ReminderIntervalMinutes=m;return new(s,n);}
static void Boundaries(){var s=D();A.True(ScheduleEvaluator.Evaluate(At(17,9),s).IsActive);A.False(ScheduleEvaluator.Evaluate(At(17,18),s).IsActive);}
static void Overnight(){var s=D();s.Schedule[DayOfWeek.Monday]=new(){IsEnabled=true,Start=new(22,0),End=new(2,0)};A.True(ScheduleEvaluator.Evaluate(At(17,23),s).IsActive);A.True(ScheduleEvaluator.Evaluate(At(18,1),s).IsActive);A.False(ScheduleEvaluator.Evaluate(At(18,2),s).IsActive);}
static void SundayMonday(){var s=D();foreach(var x in s.Schedule.Values)x.IsEnabled=false;s.Schedule[DayOfWeek.Sunday]=new(){IsEnabled=true,Start=new(22,0),End=new(2,0)};A.True(ScheduleEvaluator.Evaluate(At(17,1),s).IsActive);}
static void IntervalChange(){var n=At(17,10);var e=E(n);var s=D();s.ActiveScheduleEnabled=false;s.ReminderIntervalMinutes=10;e.UpdateSettings(s,n.AddMinutes(5));A.Eq(ReminderState.Running,e.Tick(n.AddMinutes(14)).State);A.Eq(ReminderState.ReminderDue,e.Tick(n.AddMinutes(15)).State);}
static void Snooze(){var n=At(17,10);var e=E(n,1);e.Tick(n.AddMinutes(1));e.Snooze(n.AddMinutes(1),TimeSpan.FromMinutes(5));A.Eq(ReminderState.Snoozed,e.Tick(n.AddMinutes(5)).State);A.Eq(ReminderState.ReminderDue,e.Tick(n.AddMinutes(6)).State);}
static void Pause(){var n=At(17,10);var e=E(n,1);e.PauseUntil(n.AddMinutes(30));A.Eq(ReminderState.Paused,e.Tick(n.AddMinutes(20)).State);A.Eq(ReminderState.Running,e.Tick(n.AddMinutes(30)).State);A.Eq(ReminderState.ReminderDue,e.Tick(n.AddMinutes(31)).State);}
static void NoBacklog(){var s=D();s.ReminderIntervalMinutes=1;var e=new ReminderEngine(s,At(17,17,59));A.Eq(ReminderState.InactiveSchedule,e.Tick(At(17,18)).State);A.Eq(ReminderState.Running,e.Tick(At(18,9)).State);A.Eq(ReminderState.ReminderDue,e.Tick(At(18,9,1)).State);}
static void SessionResume(){var n=At(17,10);var e=E(n,1);e.SetSessionActive(false,n);A.Eq(ReminderState.SessionInactive,e.Tick(n.AddMinutes(20)).State);e.SetSessionActive(true,n.AddMinutes(20));A.Eq(ReminderState.Running,e.Tick(n.AddMinutes(20)).State);A.Eq(ReminderState.ReminderDue,e.Tick(n.AddMinutes(21)).State);}
static async Task CorruptSettings(){var p=Path.Combine(Path.GetTempPath(),$"teyemer-{Guid.NewGuid():N}.json");try{await File.WriteAllTextAsync(p,"{bad");var s=await new JsonSettingsStore(p).LoadAsync();A.Eq(20,s.ReminderIntervalMinutes);A.True(s.ActiveScheduleEnabled);}finally{if(File.Exists(p))File.Delete(p);}}
static void StartupQuote(){var c=StartupRegistrationService.BuildCommand(@"C:\Program Files\Teyemer\Teyemer.App.exe",true);A.True(c.StartsWith('"'));A.True(c.EndsWith(" --minimized"));A.True(c.Contains("Program Files"));}
static void PopupRange(){var s=D();s.PopupDismissSeconds=0;s.Normalize();A.Eq(1,s.PopupDismissSeconds);s.PopupDismissSeconds=61;s.Normalize();A.Eq(60,s.PopupDismissSeconds);}
static class A{public static void True(bool v){if(!v)throw new Exception("expected true");}public static void False(bool v)=>True(!v);public static void Eq<T>(T e,T a){if(!EqualityComparer<T>.Default.Equals(e,a))throw new Exception($"expected {e}, actual {a}");}}
